### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by ekohl** [rodjek/vim-puppet#104]
I'd like to include vim-puppet in Fedora but it'd be useful if there were tags. Has this been considered?

**Comment by lelutin** [comment]
@rodjek fwiw this would probably also help out with debian packaging

**Comment by lelutin** [comment]
fwiw I'm super close to creating tag 1.0.0. There's just one last bug that I'm trying to get rid of before this happens (e.g. #136 )

**Comment by ekohl** [comment]
Any update on this?

**Comment by lelutin** [comment]
@ekohl hello! I don't know if you're still interested in packaging the plugin, but I've just *finally* pushed a tag for version 1.0.0

This module will be following SemVer for versioning
