### ISSUE TITLE
The colon character should not be a keyword

### ISSUE THREAD

**Issue by SamK** [rodjek/vim-puppet#108]
Hi Tim, Hi all,

The colon `:` character should not be a keyword.

I tend to like having organized folders and it annoys me a lot when the colon character is considered as a word, it makes annoying to navigate inside class names, especially when refactoring or copy/pasting parts of it.

I can provide a PR if you want.

**Comment by lelutin** [comment]
here's another reason not to include the colon in iskeyword. with the follwing:

~~~
file { $variable:
  ensure => present,
  [...]
~~~

place the cursor on `variable` and hit `#` to search for other occurences of the variable. It'll actually search for `variable:` and might not find anything.
