### ISSUE TITLE
Problem with gutentags.vim

### ISSUE THREAD

**Issue by consal** [rodjek/vim-puppet#110]
I installed the plugin with pathogen. I'm getting the following problem when I try to open vim:

```
Error detected while processing /root/.vim/bundle/vim-puppet/after/plugin/gutentags.vim:
line    1:
E15: Invalid expression: !exists('g:gutentags_enabled' && g:gutentags_dont_load != 0 )^M
line    9:
E488: Trailing characters
line   11:
E171: Missing :endif
Press ENTER or type command to continue
```

Could you help?

**Comment by rodjek** [comment]
The `^M` at the end of the invalid expression looks like your git installation is not normalising the line endings during checkout. Try setting `core.autocrlf` in git (`git config --global core.autocrlf true`) and then reinstalling the plugin.

**Comment by consal** [comment]
Indeed you were right about the git configuration, thanks! :)
