### ISSUE TITLE
Slashes in pathnames confuse the highlighting

### ISSUE THREAD

**Issue by petdance** [rodjek/vim-puppet#120]
I ran `facter > foo.pp` and then `vim foo.pp` to take a look at it.  The section on mountpoints had incorrect highlighting because of slashes in the paths.  The first mountpoint is highlighted correctly, but the second is not.

![Screen Shot 2019-11-14 at 3 25 29 PM](https://user-images.githubusercontent.com/41100/68897762-c3cc7f00-06f3-11ea-8fda-6c0e2d4d07c9.png)

In the screenshot above, I put the `/` in quotes as `"/"` to make it highlight correctly, but left the `/boot` unquoted so that it messes up the highlighting.

**Comment by rodjek** [comment]
In my opinion, this is the expected behaviour. `/boot` is not a valid bare string so it's highlighting it as a multiline regex, which is also how Puppet treats it

```
$ puppet parser validate test.pp
Error: Could not parse for environment production: Syntax error at '/' (file: /home/tsharpe/code/rodjek/rspec-puppet/test.pp, line: 2, column: 3)
$ cat test.pp
$foo = {
  /boot => 'bar',
}
```

**Comment by lelutin** [comment]
@petdance I agree with @rodjek that this behavior is to be expected. here's my take on it:

1. facter does *not* output content suitable for puppet manifests. Its format is ... rather unclear. it looks very close to ruby hashes / puppet hashes but it does not respect all of the same constraints.
2. in puppet manifests, the `/` before `boot` delimits a regular expression. that's the coloring that's showing up till the end of the file. regexps can span multiple lines in puppet manifests and they're terminated by another unescaped `/`.

if you wish to reuse the output of facter directly in puppet as a datastructure, I would suggest that you use either `facter --yaml` or `--json` and redirect that to a file that hiera is setup to read -- or if you just wish to do a visual inspection you can combine the json output with `jq`.

very late reply.... but hope that helps!

**Comment by petdance** [comment]
Sounds reasonable to me. And I know all too well about not replying to tickets until years later... :-)

We're all Terraform and Ansible now anyway. :-)
