### ISSUE TITLE
Using vim-yardoc for puppet files

### ISSUE THREAD

**Issue by misaflo** [rodjek/vim-puppet#125]
Hi,

It would be nice if we could have YARD tag highlighting using [vim-yardoc](https://github.com/noprompt/vim-yardoc) (don't know if modifications must be done in vim-puppet, vim-yardoc or both).

Issue also [reported on vim-yardoc](https://github.com/noprompt/vim-yardoc/issues/8).

**Comment by lelutin** [comment]
Allowing coloration for YARD tags would be great. I'm not sure yet how that could be implemented. Would we need to have the same kind of mechanism than for epp where inside some region (in that case delimited by opening and closing tags) the whole syntax file gets included?

if you're willing to try that out, you can check out how it was done for epp and try and mimic? check out syntax/embeddedpuppet.vim. if my idea is not too far fetched, we'd include the yardoc syntax into the `puppetComment` syntax group.

if that seems to work out, then we'll have to figure out a way to make that conditional to the syntax file being present on the system.

**Comment by lelutin** [comment]
fwiw I've sent a PR for this on vim-yardoc. if it gets merged in I'll send a PR to this project to update the readme with a mention about the possibility to use that other plugin for yard hilighting
