### ISSUE TITLE
Hash Rocket aligning happens in comments

### ISSUE THREAD

**Issue by russellshackleford** [rodjek/vim-puppet#143]
#### Vim version

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug  2 2022 12:56:59)
Included patches: 1-1763
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>

#### OS:

AlmaLinux release 8.7 (Stone Smilodon)

### Problem: AlignHashRockets doesn't understand comments

Presumably it doesn't catch the end `}` of whatever resource it is aligning and therefore aligns _ALL_ hash rockets in the entirety of my puppet-strings comments anytime the function is called. I can introduce a delay between typing the `=` and the `>` to workaround this.

Attached is a short gif showing the problem
![align-hash-rockets](https://user-images.githubusercontent.com/22574539/208781963-a137ed57-9b35-48ab-8caf-7eea04646bf6.gif)

**Comment by lelutin** [comment]
I've just tried this out with the example comment in the animation and I can reproduce this on top of current master.

So I'll start by formulating a test for this. Then we can work towards fixing the issue.
