### ISSUE TITLE
Plugin breaks usage of `gq` for formatting comments

### ISSUE THREAD

**Issue by lollipopman** [rodjek/vim-puppet#145]
As mentioned in https://github.com/rodjek/vim-puppet/pull/92#issuecomment-382922642 when this plugin is enabled you can no longer use `gq` to break up long comment lines in puppet code.

**Comment by lelutin** [comment]
Hello @lollipopman (and sorry for the 1y delay)

the plugin currently can break up long lines, as we test in https://github.com/rodjek/vim-puppet/blob/master/test/format/textwidth.vader -- however it's only doig it if `textwidth` is set.gt
