### ISSUE TITLE
=> alignment is too aggressive

### ISSUE THREAD

**Issue by 3flex** [rodjek/vim-puppet#28]
I have some code that I think should look like this:

``` puppet
mysql::server::config { 'basic_config':
  settings => {
    'mysqld' => {
      'collation-server' => 'utf8_unicode_ci',
      'delay-key-write'  => 'off',
    },
  }
}
```

When formatted like this, the automatic `=>` alignment doesn't just affect the lines in the `mysqld` hash but the two lines above it as well, so you get this:

``` puppet
mysql::server::config { 'basic_config':
  settings               => {
    'mysqld'             => {
      'collation-server' => 'utf8_unicode_ci',
      'delay-key-write'  => 'off',
    },
  }
}
```

I've love it just to affect the items inside each `{ ... }` without changing any child or parent `{ ... }`. Wish I had a PR for you but I wouldn't know where to start :(

**Comment by danshultz** [comment]
Thanks for updating this @rodjek :heart:
