### ISSUE TITLE
until some code has been written, opening a file and running :Tab causes error

### ISSUE THREAD

**Issue by thoraxe** [rodjek/vim-puppet#33]
If you just open a .pp file and then find a section and run :Tab with tabular:

```
Tabularize hasn't been called yet; no pattern/command to reuse!
```

It's not until I type in some kind of complete puppet resource (ex: file) that I'm able to do that.

For example, this is not sufficient:

``` puppet
file { '/foo/bar': }
```

I actually have to do something like:

``` puppet
file { '/foo/bar':
  ensure => present,
}
```

Before I can go to another section and then type :Tab.

I'm not sure if this is a bug or an unintended consequence.

**Comment by rodjek** [comment]
The dependency on Tabularize has been removed as part of #64, so this should no longer be a problem.
