### ISSUE TITLE
Does not properly highlight parameterized classes

### ISSUE THREAD

**Issue by jesusaurus** [rodjek/vim-puppet#4]
Only the first parameter of a parameterized class is properly highlighted when using hiera for default values.

Example snippet:

```
class foo::bar (
  $var1 = hiera("var1"),
  $var2 = hiera("var2"),
) inherits foo::baz {
  #code
}
```

$var1 is correctly highlighted, but $var2 is not.

**Comment by natemccurdy** [comment]
Just wanted to chime in and say that this is still an issue as of 4793b07

**Comment by lelutin** [comment]
@rodjek your last comment here (and the corresponding work) is from 2013, is it still in your plans to merge this onto master? if so, do you need help in order to finish some features or maybe write some tests to ensure that the new code doesn't break anything?

**Comment by lelutin** [comment]
@jesusaurus I've just tested your case again on current master and the new syntax highlighting that got merged in seems to have fixed this.

please re-open if you're still seeing this problem!
