### ISSUE TITLE
Closing braces sometimes wrong colour

### ISSUE THREAD

**Issue by alexharv074** [rodjek/vim-puppet#47]
I'm using the latest version on Mac OS X.

If I create a file /tmp/foo.pp and give it content:

```
class foo {
  notify { 'test': }
} 
```

Class is pink, opening braces are black and closing braces are pink.  If I change the content to:

```
file { 'foo':
  ensure => file,
}
```

Now file is brown, opening brace is black and closing brace is pink.  If I change the content to:

```
foo::bar { 'foo':
  ensure => present,
}
```

Now foo::bar and opening brace is pink, as is the closing brace.

**Comment by tuxinaut** [comment]
:+1: Same here

**Comment by lelutin** [comment]
This seems to be caused by the region for class/file/define ending with the opening curly brace.

my suggestion here would be to drop colouring of braces to avoid having some cases that get coloured and some not.

**Comment by lelutin** [comment]
I've just verified the three cases on current master, and I believe that the recent merger of the new syntax highlighting fixed all three cases.
