### ISSUE TITLE
How to update one plugin at a time ?

### ISSUE THREAD

**Issue by mayuroks** [rodjek/vim-puppet#49]
I have multiple plugins. I just wanna update one. Is there a way to do that?
Right now I only know of using PluginInstall!  .... I tried adding arguements to this command and it failed.

Can you tell me how to do it ?

**Comment by lmayorga1980** [comment]
if you have a `~/.vimrc.bundles.local` just comment it out the plugins you don't want to update.

```
Bundle '<plugin-a>'
#Bundle '<plugin-b>'
```
