### ISSUE TITLE
Vim-puppet does not seem to work on CentOS7

### ISSUE THREAD

**Issue by 030** [rodjek/vim-puppet#50]
Placing all files in /home/vagrant/.vim does not seem to enable vim-puppet on CentOS 7 as using vim to change puppet .pp files is unchanged.

```
[vagrant@localhost .vim]$ ls
after  ftdetect  ftplugin  indent  README.md  syntax
```

**Comment by tuxinaut** [comment]
I think you should take a look at [Vundle](https://github.com/gmarik/Vundle.vim) or Pathogen (https://github.com/tpope/vim-pathogen)

With these tools you can easly manage your vim pluigns.
