### ISSUE TITLE
Syntax highlight improvement

### ISSUE THREAD

**Issue by zoresvit** [rodjek/vim-puppet#54]
Hi. Are there any plans to merge the `new_syntax_highlighting` branch into `master`? It fixes numerous problems, like highlighting of comments and functions in class arguments list:

Broken highlighting:
![Puppet wrong syntax](http://s2.postimg.org/70qfh0vmh/2015_04_14_144800_1082x305_scrot.png)

Correct highlighting:
![Puppet correct syntax](http://s8.postimg.org/9kv1medol/2015_04_14_145202_1045x306_scrot.png)

**Comment by tuxinaut** [comment]
Any updates on this topic?

**Comment by zoresvit** [comment]
Unfortunately this seems not to be maintained much anymore.
