### ISSUE TITLE
it is not effect when i download by vundle

### ISSUE THREAD

**Issue by gecheng19800707** [rodjek/vim-puppet#61]
it is not effect when i download by vundle

i have to copy all file to vimfiles folder

but vundle download them to /vimfiles/bundle/vim-puppet 

it will not effect

**Comment by stefanlasiewski** [comment]
Hi Gecheng,

I'm not affiliated with this project, but I thought I would quickly try to provide some advice.

If this plugin does not work in your set up, then it is most likely an issue with your local Vundle setup. If this was actually a problem with vim-puppet, then vim-puppet would print errors to your screen. From your description  ("i have to copy all file to vimfiles folder"), it sounds a bit like Vundle is installing the plugins to the wrong directory, and you will need to read the Vundle documentation to get help with that.

I recommend that you make sure that your Vundle install follows the guide here. My ~/.vimrc uses this syntax almost exactly, and it works for me. However, I use MacOSX & Linux. You may be using Windows.

https://github.com/VundleVim/Vundle.vim/blob/master/README.md#quick-start

**Comment by rodjek** [comment]
Closing as this seems to not be a problem with vim-puppet
