### ISSUE TITLE
Interaction with nerdcommenter

### ISSUE THREAD

**Issue by amateo** [rodjek/vim-puppet#62]
Hi,

I've been using vim-puppet and nerd commenter for a time. Since I upgraded my system from ubuntu 14.04 to 16.04, although I have preserved my whole `.vim` directory, when I comment code with \cc it is commented with `/* */` instead of `#`.
Any help on how to to change this behaviour?

**Comment by rodjek** [comment]
Sounds like vim isn't detecting the files as Puppet files properly. What's the output of `:set ft?` in vim when you have a `.pp` file open?

**Comment by amateo** [comment]
Sorry, don't worry about this. I removed the vim-scripts package (ubuntu) where the nerd commenter is provided and installed it from git and it worked again. In the process I installed/reconfigured a lot of things so I can't be sure what was the exact thing that fixed it.
