### ISSUE TITLE
Merging vim-puppet with puppetlabs/puppet/ext/vim

### ISSUE THREAD

**Issue by shibumi** [rodjek/vim-puppet#69]
Hello,
Is there any reason why don't push your awesome vim plugin to the puppet repository by puppetlabs?
They seem to have a `ext` directory that includes a really old puppet.vim... It would be nice if you could push your puppet.vim into puppetlabs/puppet/ext/vim

https://github.com/puppetlabs/puppet/tree/ebd96213cab43bb2a8071b7ac0206c3ed0be8e58/ext/vim

**Comment by davewongillies** [comment]
As of https://github.com/puppetlabs/puppet/commit/018a26b2c4f8e822f5ceb9efdaa414629bba1db5#diff-dc84d886f3fac8e41dc514c8ddfccf34 puppet.vim has been removed from https://github.com/puppetlabs/puppet, so this issue can be closed
