### ISSUE TITLE
Copyright/license missing

### ISSUE THREAD

**Issue by apoikos** [rodjek/vim-puppet#79]
Hi,

I'm looking into packaging this plugin for Debian, to replace the old vim-puppet package that was created from the original vim plugin shipped in the Puppet source. I noticed that copyright/license info is missing, which makes uploading the package to the Debian archive a no-go.

Would it be possible to include explicit copyright information in the repository?

Regards,
Apollon

P.S.: Just in case it helps, to my understanding you probably should license the plugin under Apache-2.0, since that was the license of the original files that served as a basis for this plugin.

**Comment by ge-fa** [comment]
Ping.. What's the current state here?

**Comment by thomasvs** [comment]
I would also appreciate there being a Debian package.

Tim, here's a pull request to make things easier - just a click away.

https://github.com/thomasvs/vim-puppet/pull/1

**Comment by lelutin** [comment]
@rodjek what do you think about the suggestion here to apply the apache 2.0 license to this vim plugin? doing so would make it possible to package the plugin in debian as was mentioned earlier.
