### ISSUE TITLE
Align => when doing gg=G

### ISSUE THREAD

**Issue by dal00** [rodjek/vim-puppet#82]
I'm trying to align rockets => but I have realized that they are only aligned when I write them out one by one.
Why are they not aligned when doing gg=G ? I have a vague memory that this has worked. But I'm not sure. Tried to revert some related changes but did not really help.
Or is there another way to align a whole file?

The workaround is to bind puppet-lint -f but that is not as nice as having it built in :)

**Comment by mandos** [comment]
@dal00  Check PR #92, maybe it's you looking for.

**Comment by rodjek** [comment]
Fixed in #92
