### ISSUE TITLE
structured variables in strings are not highlighted

### ISSUE THREAD

**Issue by genebean** [rodjek/vim-puppet#98]
![image](https://user-images.githubusercontent.com/966789/47793055-c2e8cb00-dcf3-11e8-874a-9eebe158dccd.png)

```puppet
$facts['os']['family']
$foo = "Random bar ${unstructured} ${facts['kernel']}"
```

In the above example you can see that `${unstructured}` is properly highlighted while `${facts['kernel']}` is not. This happens with any kind of hash variable in a string (not just facts)

As a side note, I submitted a related issue for VS Code at https://github.com/lingua-pupuli/puppet-editor-syntax/issues/16

**Comment by GerbenWelter** [comment]
This seems to be already fixed by #75.

**Comment by lelutin** [comment]
@genebean I believe that the new syntax highlight (as it is on current master) has fixed this issue. the `${}` itself gets no coloring, but variable names should be highlighted properly for both unstructured and structured variables.

please reopen if you are still seeing this problem.

**Comment by genebean** [comment]
Very nice! Thanks.
<img width="389" alt="Screen Shot 2019-09-16 at 7 05 47 AM" src="https://user-images.githubusercontent.com/966789/64953280-7301ec80-d850-11e9-922a-dd48ac20dc5b.png">
